{"name": "test_create_alerts_for_failed_tasks", "status": "passed", "steps": [{"name": "Create a Task and complete it with failure", "status": "passed", "start": 1733724312281, "stop": 1733724312590}, {"name": "Verify that alert entries are created for the failed task", "status": "passed", "start": 1733724312590, "stop": 1733724312656}, {"name": "Verify that appropriate logs are created for the failed task", "status": "passed", "start": 1733724312656, "stop": 1733724312688}], "start": 1733724312280, "stop": 1733724312688, "uuid": "b80f51c5-a14f-4e0e-8bf1-6b577814c575", "historyId": "e5198e0c9c757e48f80a88d00832da4f", "testCaseId": "e5198e0c9c757e48f80a88d00832da4f", "fullName": "user.tests.test_big_data#test_create_alerts_for_failed_tasks", "labels": [{"name": "feature", "value": "Alert Management"}, {"name": "story", "value": "Create Alerts for Failed Tasks"}, {"name": "tag", "value": "django_db"}, {"name": "parentSuite", "value": "user.tests"}, {"name": "suite", "value": "test_big_data"}, {"name": "host", "value": "SHPatsnapB0008"}, {"name": "thread", "value": "49308-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "user.tests.test_big_data"}]}